/**
 * FinalReportViewer
 *
 * Displays the structured KYC final report generated by the Final Report agent.
 * Organized into sections matching the report schema.
 */

import React, { useState } from 'react';
import {
  FileText,
  User,
  Shield,
  Building2,
  Fingerprint,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  ChevronDown,
  ChevronRight,
} from 'lucide-react';
import { FinalReport } from '@/services/admin.service';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function ScorePill({ score, label }: { score: number | null; label: string }) {
  if (score === null) return null;
  const pct = Math.round(score * 100);
  const color = pct >= 80 ? 'text-emerald-700 bg-emerald-50' :
                pct >= 60 ? 'text-amber-700 bg-amber-50' :
                            'text-red-700 bg-red-50';
  return (
    <div className={`flex items-center gap-2 px-3 py-2 rounded-lg ${color}`}>
      <span className="text-xs font-medium">{label}</span>
      <span className="text-base font-bold">{pct}%</span>
    </div>
  );
}

function BoolPill({ value, label }: { value: boolean; label: string }) {
  return (
    <div className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium ${
      value ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'
    }`}>
      {value
        ? <CheckCircle2 className="w-3.5 h-3.5" />
        : <XCircle className="w-3.5 h-3.5" />
      }
      {label}
    </div>
  );
}

function SectionHeader({ icon: Icon, title }: { icon: React.ElementType; title: string }) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <Icon className="w-4 h-4 text-neutral-500" />
      <h4 className="text-sm font-semibold text-neutral-700">{title}</h4>
    </div>
  );
}

function DataRow({ label, value }: { label: string; value: React.ReactNode }) {
  if (value === null || value === undefined || value === '') return null;
  return (
    <div className="flex items-start gap-3 py-1.5 border-b border-neutral-50 last:border-0">
      <span className="text-xs text-neutral-500 w-36 flex-shrink-0">{label}</span>
      <span className="text-xs text-neutral-800 font-medium break-all">{value}</span>
    </div>
  );
}

// ─── Section components ──────────────────────────────────────────────────────

function CollapsibleSection({
  title,
  children,
  defaultOpen = true,
}: {
  title: string;
  children: React.ReactNode;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="border border-neutral-200 rounded-xl overflow-hidden mb-4">
      <button
        className="w-full flex items-center justify-between px-4 py-3 bg-neutral-50 hover:bg-neutral-100 transition-colors text-left"
        onClick={() => setOpen(!open)}
      >
        <span className="text-sm font-semibold text-neutral-800">{title}</span>
        {open ? <ChevronDown className="w-4 h-4 text-neutral-400" /> : <ChevronRight className="w-4 h-4 text-neutral-400" />}
      </button>
      {open && <div className="px-4 py-3">{children}</div>}
    </div>
  );
}

// ─── Main component ────────────────────────────────────────────────────────

interface FinalReportViewerProps {
  report: FinalReport;
}

export function FinalReportViewer({ report }: FinalReportViewerProps) {
  const data = report.report as Record<string, any> | null;
  if (!data) return <p className="text-sm text-neutral-500">Report data unavailable.</p>;

  const submitted = data.customer_submitted_details ?? {};
  const ocr = data.ocr_extracted_details ?? {};
  const wf = data.workflow_results ?? {};
  const flags = data.fraud_compliance_flags ?? {};
  const scores = data.scores_summary ?? {};

  const rec = report.recommended_action;

  return (
    <div>
      {/* Scores overview */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
        <ScorePill score={report.final_confidence_score} label="Identity Confidence" />
        <ScorePill score={report.document_quality_score} label="Doc Quality" />
        <ScorePill score={scores.name_match_score} label="Name Match" />
        <ScorePill score={scores.government_match_score} label="Gov Match" />
      </div>

      {/* Status flags */}
      <div className="flex flex-wrap gap-2 mb-4">
        <BoolPill value={report.identity_verified} label="Identity Verified" />
        <BoolPill value={report.compliance_passed} label="Compliance Passed" />
        <BoolPill value={report.government_validated} label="Gov Validated" />
        <BoolPill value={!report.fraud_detected} label="No Fraud" />
        <BoolPill value={!report.document_quality_score || report.document_quality_score > 0.5} label="Good Doc Quality" />
      </div>

      {/* Recommendation */}
      {rec && (
        <div className={`mb-4 px-4 py-3 rounded-xl text-sm font-semibold flex items-center gap-2 ${
          rec === 'approve' ? 'bg-emerald-100 text-emerald-800' :
          rec === 'reject' ? 'bg-red-100 text-red-800' :
          'bg-amber-100 text-amber-800'
        }`}>
          {rec === 'approve' && <CheckCircle2 className="w-4 h-4" />}
          {rec === 'reject' && <XCircle className="w-4 h-4" />}
          {rec === 'manual_review' && <AlertTriangle className="w-4 h-4" />}
          Recommended Action: <span className="capitalize">{rec.replace('_', ' ')}</span>
        </div>
      )}

      {/* Customer details */}
      <CollapsibleSection title="Customer Submitted Details">
        <SectionHeader icon={User} title="Applicant Information" />
        <DataRow label="First Name" value={submitted.first_name} />
        <DataRow label="Last Name" value={submitted.last_name} />
        <DataRow label="Date of Birth" value={submitted.date_of_birth} />
        <DataRow label="Nationality" value={submitted.nationality} />
        <DataRow label="Address" value={submitted.address} />
        <DataRow label="ID Type" value={submitted.id_type} />
        <DataRow label="ID Number" value={submitted.id_number} />
        <DataRow label="Phone" value={submitted.phone} />
        <DataRow label="Email" value={submitted.email} />
      </CollapsibleSection>

      {/* OCR extracted */}
      <CollapsibleSection title="OCR Extracted Details">
        <DataRow label="Extracted Name" value={ocr.extracted_name} />
        <DataRow label="Extracted DOB" value={ocr.extracted_dob} />
        <DataRow label="Extracted ID" value={ocr.extracted_id_number} />
        <DataRow label="Extracted Address" value={ocr.extracted_address} />
        <DataRow label="Documents Processed" value={ocr.ocr_document_count} />
      </CollapsibleSection>

      {/* Workflow results */}
      <CollapsibleSection title="Workflow Results">
        {/* Document analysis */}
        {wf.document_analysis && (
          <div className="mb-3">
            <SectionHeader icon={FileText} title="Document Analysis" />
            <DataRow label="Status" value={wf.document_analysis.status} />
            <DataRow label="Quality Score" value={wf.document_analysis.quality_score != null ? `${(wf.document_analysis.quality_score * 100).toFixed(0)}%` : null} />
            <DataRow label="Completeness" value={wf.document_analysis.completeness_score != null ? `${(wf.document_analysis.completeness_score * 100).toFixed(0)}%` : null} />
            <DataRow label="Doc Type" value={wf.document_analysis.document_type} />
            <DataRow label="Tampering" value={wf.document_analysis.tampering_flag ? '⚠ Suspected' : '✓ None detected'} />
            <DataRow label="Summary" value={wf.document_analysis.summary} />
          </div>
        )}
        {/* Compliance */}
        {wf.compliance_review && (
          <div className="mb-3">
            <SectionHeader icon={Shield} title="Compliance Review" />
            <DataRow label="Status" value={wf.compliance_review.status} />
            <DataRow label="Flags" value={(wf.compliance_review.flags || []).join(', ') || 'None'} />
            <DataRow label="PEP" value={wf.compliance_review.pep_result ? 'Flagged' : 'Clear'} />
            <DataRow label="Sanctions" value={wf.compliance_review.sanctions_result ? 'Match Found' : 'Clear'} />
            <DataRow label="Summary" value={wf.compliance_review.summary} />
          </div>
        )}
        {/* Government */}
        {wf.government_validation && (
          <div className="mb-3">
            <SectionHeader icon={Building2} title="Government Validation" />
            <DataRow label="Status" value={wf.government_validation.status} />
            <DataRow label="Match Score" value={wf.government_validation.match_score != null ? `${(wf.government_validation.match_score * 100).toFixed(0)}%` : null} />
            <DataRow label="Reference ID" value={wf.government_validation.reference_id} />
            <DataRow label="Summary" value={wf.government_validation.summary} />
          </div>
        )}
        {/* Identity */}
        {wf.identity_verification && (
          <div>
            <SectionHeader icon={Fingerprint} title="Identity Verification" />
            <DataRow label="Status" value={wf.identity_verification.status} />
            <DataRow label="Confidence" value={wf.identity_verification.confidence_score != null ? `${(wf.identity_verification.confidence_score * 100).toFixed(0)}%` : null} />
            <DataRow label="Name Match" value={wf.identity_verification.name_match_score != null ? `${(wf.identity_verification.name_match_score * 100).toFixed(0)}%` : null} />
            <DataRow label="DOB Match" value={wf.identity_verification.dob_match === true ? '✓ Match' : wf.identity_verification.dob_match === false ? '✗ Mismatch' : null} />
            <DataRow label="ID Match" value={wf.identity_verification.id_match === true ? '✓ Match' : wf.identity_verification.id_match === false ? '✗ Mismatch' : null} />
            <DataRow label="Duplicate" value={wf.identity_verification.duplicate_detected ? '⚠ Detected' : '✓ None'} />
            <DataRow label="Fraud Flag" value={wf.identity_verification.fraud_flag ? '⚠ Yes' : '✓ No'} />
            <DataRow label="Summary" value={wf.identity_verification.summary} />
          </div>
        )}
      </CollapsibleSection>

      {/* Fraud / Compliance flags */}
      {(flags.fraud_flags?.length > 0 || flags.compliance_flags?.length > 0) && (
        <CollapsibleSection title="Fraud & Compliance Flags" defaultOpen={false}>
          {flags.fraud_flags?.length > 0 && (
            <div className="mb-2">
              <p className="text-xs font-semibold text-neutral-600 mb-1">Fraud Flags</p>
              <div className="flex flex-wrap gap-1.5">
                {flags.fraud_flags.map((f: string) => (
                  <span key={f} className="px-2 py-0.5 bg-red-50 text-red-700 text-xs rounded-full border border-red-200">
                    {f}
                  </span>
                ))}
              </div>
            </div>
          )}
          {flags.compliance_flags?.length > 0 && (
            <div>
              <p className="text-xs font-semibold text-neutral-600 mb-1">Compliance Flags</p>
              <div className="flex flex-wrap gap-1.5">
                {flags.compliance_flags.map((f: string) => (
                  <span key={f} className="px-2 py-0.5 bg-amber-50 text-amber-700 text-xs rounded-full border border-amber-200">
                    {f}
                  </span>
                ))}
              </div>
            </div>
          )}
        </CollapsibleSection>
      )}
    </div>
  );
}
